### ISSUE TITLE
Akash Provider Fails to Start

### ISSUE THREAD

**Issue by dougbebber** [HandyOSS/HandyHost#69]
Everything appears to be working except that the Provider is offline and will not successfully start.
I keep seeing the following in the /var/log/handyhost.log:

AKT: get aggregates query error Error: post failed: Post "http://rpc-1.handyhost.computer/": dial tcp: address rpc-1.handyhost.computer: missing port in address

AKT: get aggregates query error Error: post failed: Post "http://rpc-1.handyhost.computer/": dial tcp: address rpc-1.handyhost.computer: missing port in address

AKT: get aggregates query error Error: post failed: Post "http://rpc-1.handyhost.computer/": dial tcp: address rpc-1.handyhost.computer: missing port in address

AKT: get aggregates query error Error: post failed: Post "http://rpc-1.handyhost.computer/": dial tcp: address rpc-1.handyhost.computer: missing port in address

AKT: get aggregates query error Error: post failed: Post "http://rpc-1.handyhost.computer/": dial tcp: address rpc-1.handyhost.computer: missing port in address

error calling http://rpc-1.handyhost.computer:26659/akash1ghhkmp9c0zwynvktefh2uu0saam2dzw04pf52m Error: connect ECONNREFUSED [72.8.228.138:26659](http://72.8.228.138:26659/)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
errno: -111,
code: 'ECONNREFUSED',
syscall: 'connect',
address: '72.8.228.138',
port: 26659
}

Any known solution?

**Comment by alexsmith540** [comment]
Are you on the latest v0.5.2 build?

**Comment by dougbebber** [comment]
Yes, I installed  handyhost_v0.5.2.1.deb on Ubuntu 20.04 LTS.

Handy Host shows:
HandyHost v0.5.2
Akash v0.14.1

**Comment by dougbebber** [comment]
Yes, I installed handyhost_v0.5.2.1.deb on Ubuntu 20.04 LTS.

Handy Host shows:
HandyHost v0.5.2
Akash v0.14.1

> Are you on the latest v0.5.2 build?
> […](#)
> Sent from my iPhone
> On Mar 12, 2022, at 7:53 AM, Douglas Bebber ***@***.***> wrote: ﻿ Everything appears to be working except that the Provider is offline and will not successfully start. I keep seeing the following in the /var/log/handyhost.log: AKT: get aggregates query error Error: post failed: Post "http://rpc-1.handyhost.computer/": dial tcp: address rpc-1.handyhost.computer: missing port in address AKT: get aggregates query error Error: post failed: Post "http://rpc-1.handyhost.computer/": dial tcp: address rpc-1.handyhost.computer: missing port in address AKT: get aggregates query error Error: post failed: Post "http://rpc-1.handyhost.computer/": dial tcp: address rpc-1.handyhost.computer: missing port in address AKT: get aggregates query error Error: post failed: Post "http://rpc-1.handyhost.computer/": dial tcp: address rpc-1.handyhost.computer: missing port in address AKT: get aggregates query error Error: post failed: Post "http://rpc-1.handyhost.computer/": dial tcp: address rpc-1.handyhost.computer: missing port in address error calling http://rpc-1.handyhost.computer:26659/akash1ghhkmp9c0zwynvktefh2uu0saam2dzw04pf52m Error: connect ECONNREFUSED 72.8.228.138:26659 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) { errno: -111, code: 'ECONNREFUSED', syscall: 'connect', address: '72.8.228.138', port: 26659 } Any known solution? — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you are subscribed to this thread.

**Comment by alexsmith540** [comment]
i think the errors you were seeing in the logs were likely due to an rpc outage on our aggregates node yesterday morning. 
If you try to run the provider now do you still see any errors?

**Comment by dougbebber** [comment]
I no longer receive that error. However, each time I attempt to start the Provider, I initially get a dialog that says started Provider successfully. Then the provider status indicator in the upper right goes dark and the Provider entry on the left sidebar has a yellow exclamation point.
![Provider1](https://user-images.githubusercontent.com/2474050/158077990-3e333731-d6e9-4ebc-a57b-c6e129e907d6.png)
![Provider2](https://user-images.githubusercontent.com/2474050/158077995-8db1e45f-10db-4eed-a207-9d241fc4490f.png)

/var/log/handyhost.log now contains:
akash exists?? true
akash dir exists? true
is positional [ 'api', 'getIP' ]
is positional [ 'api', 'akt', 'getClusterConfig' ]
is positional [ 'api', 'akt', 'getMarketAggregates' ]
is positional [ 'api', 'akt', 'getClusterStats' ]
is positional [ 'api', 'akt', 'runProvider' ]
should akash run?  true
is positional [ 'api', 'akt', 'getClusterStats' ]
is positional [ 'api', 'akt', 'getMarketAggregates' ]
is positional [ 'api', 'akt', 'getProviderLogs' ]
is positional [ 'api', 'akt', 'getProviderLogs' ]
is positional [ 'api', 'akt', 'getClusterStats' ]
is positional [ 'api', 'akt', 'getMarketAggregates' ]
is positional [ 'api', 'akt', 'getClusterConfig' ]
is positional [ 'api', 'akt', 'getProviderParams' ]
is positional [ 'api', 'akt', 'getState' ]
akash exists?? true
akash dir exists? true
is positional [ 'api', 'getIP' ]
is positional [ 'api', 'akt', 'getMarketAggregates' ]
is positional [ 'api', 'akt', 'getClusterStats' ]
is positional [ 'api', 'akt', 'runProvider' ]
should akash run?  true
is positional [ 'api', 'akt', 'getClusterStats' ]
is positional [ 'api', 'akt', 'getMarketAggregates' ]
is positional [ 'api', 'akt', 'getClusterStats' ]
is positional [ 'api', 'akt', 'getMarketAggregates' ]
is positional [ 'api', 'akt', 'providerRegistrationGasEstimate' ]
is positional [ 'api', 'akt', 'getClusterStats' ]
is positional [ 'api', 'akt', 'getMarketAggregates' ]
is positional [ 'api', 'akt', 'providerRegistrationGasEstimate' ]
is positional [ 'api', 'akt', 'providerRegistrationGasEstimate' ]
is positional [ 'api', 'akt', 'providerRegistrationGasEstimate' ]
is positional [ 'api', 'akt', 'updateProviderRegistration' ]
is positional [ 'api', 'akt', 'getClusterStats' ]
is positional [ 'api', 'akt', 'getMarketAggregates' ]
is positional [ 'api', 'akt', 'runProvider' ]
should akash run?  true
is positional [ 'api', 'akt', 'getClusterStats' ]
is positional [ 'api', 'akt', 'getMarketAggregates' ]
is positional [ 'api', 'akt', 'getClusterStats' ]
is positional [ 'api', 'akt', 'getMarketAggregates' ]
is positional [ 'api', 'akt', 'getMarketplaceOrders' ]
get orders params { page: 1, limit: 10 }
is positional [ 'api', 'akt', 'runProvider' ]
should akash run?  true
is positional [ 'api', 'akt', 'getClusterStats' ]
is positional [ 'api', 'akt', 'getMarketAggregates' ]

**Comment by dougbebber** [comment]
Here's my Cluster Nodes Resource Utilization:
![Cluster](https://user-images.githubusercontent.com/2474050/158078730-e2db3e44-28b6-4c68-a5e8-7bf7aee5e67a.png)

**Comment by alexsmith540** [comment]
Any chance you've tried a system reboot (on the provider system)? Sometimes, like the case you ran into where the rpc node was down, a provider can get stuck in an endless restarting loop which i suspect may be happening here.

**Comment by dougbebber** [comment]
Rebooted several times. Actually the machine locks up after running for several hours and I am forced to reboot.
Same problem with the akash provider. Initially start up provider, message says provider started successfully, the provider status in the right hand corner goes yellow for a few seconds, then the provider is indicated offline and the yellow exclamation is next to the "Start Provider" menu option.

**Comment by freakinfofa** [comment]
what does your networking look like? 
--are you able to see if any traffic is being blocked or dropped? (any firewalls or fancy routers you might be using?)
--ports 80 and 8443 are forwarded/NAT'd to your provider correctly? (in my case i have a reverse proxy in front of port 80 as i 
host other services under that public IP)

I know its probably the obvious... just trying to help :)

**Comment by dougbebber** [comment]
Port 80 is forwarded to the Ingress Controller machine on one of my cluster nodes. Port 8443 is forwarded to my Provider node (machine running Handy Host).

I have tried a number of things with no success getting the Provider running.

**Comment by freakinfofa** [comment]
You must open & forward ports 80 and 30000-32767 to your Ingress Controller

**Comment by avolon42x** [comment]
What you could try that helped on my side sometimes: do a `systemctl stop handyhost` followed by `killall akash` (do it twice till there is now akash proc running). `systemctl start handyhost`. Then be patient and let handyhost start the provider by itself -> if you start the provider through the ui there is the checkbox to automatically start it. If you enable it, handyhost will try and re-try to start the provider. It just took a few minutes on my setup.
