### ISSUE TITLE
dvpn unable to start after container rebuild. panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Strasser-Pablo** [HandyOSS/HandyHost#73]
I'm currently getting this error message when launching a rebuild dvpn container.

```
2022-03-31T18:04:53Z INF Querying session id=46630
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1310bbc]

goroutine 300 [running]:
github.com/sentinel-official/dvpn-node/node.(*Node).jobUpdateSessions(0xc000ea8368)
	/go/src/github.com/sentinel-official/dvpn-node/node/jobs.go:109 +0x37c
github.com/sentinel-official/dvpn-node/node.(*Node).Start.func3()
	/go/src/github.com/sentinel-official/dvpn-node/node/node.go:52 +0x1d
created by github.com/sentinel-official/dvpn-node/node.(*Node).Start
	/go/src/github.com/sentinel-official/dvpn-node/node/node.go:51 +0x125

DVPN NODE STOPPED

**Comment by alexsmith540** [comment]
we also ran into this during testing of v0.5.4, 
running the command:
```
sudo rm /root/.sentinelnode/data.db
```
worked here as well. Thanks for the info ^^^, super helpful!
